"""Neutral APRP baseline sanity tests."""

import unittest
from pathlib import Path


class TestAprpBaseline(unittest.TestCase):
    """Verify the APRP docs and version baseline stay coherent."""

    def test_readme_and_spec_share_the_public_brand(self):
        """Ensure the repo docs present APRP consistently."""
        readme = Path("README.md").read_text(encoding="utf-8")
        spec = Path("SPEC.md").read_text(encoding="utf-8")
        plan = Path("PLAN.md").read_text(encoding="utf-8")

        self.assertIn("APRP", readme)
        self.assertIn("APRP", spec)
        self.assertIn("APRP", plan)
        self.assertIn("ops/opsconfig.yaml", readme)
        self.assertIn("ops/opsconfig.yaml", spec)
        self.assertIn("/opt/aprp/checkout", readme)
        self.assertIn("storefront host", readme)
        self.assertIn("mirror hosts", readme.lower())
        self.assertIn("aprp-server", readme)
        self.assertIn("aprp-mirror", readme)
        self.assertIn("DNS-01", readme)
        self.assertIn("certbot", readme.lower())
        self.assertIn("manual TXT", readme)
        self.assertIn("docs/inventory.md", readme)
        self.assertIn("docs/purchasing.md", readme)
        self.assertIn("docs/pos.md", readme)
        self.assertIn("docs/couriers.md", readme)
        self.assertIn("docs/storefront.md", readme)
        self.assertIn("docs/showcase.md", readme)
        self.assertIn("docs/release.md", readme)
        self.assertIn("docs/install.md", readme)
        self.assertIn("docs/development.md", readme)
        self.assertIn("docs/security.md", readme)
        self.assertIn("docs/accounting.md", readme)
        self.assertIn("aprp.aprp.runtime_services", readme)
        self.assertIn("aprp.aprp.pos_services", readme)
        self.assertIn("aprp.aprp.storefront_services", readme)
        self.assertIn("aprp.aprp.showcase_services", readme)
        self.assertIn("aprp.aprp.courier_services", readme)
        self.assertIn("aprp.aprp.accounting_services", readme)
        self.assertIn("active beta", readme.lower())
        self.assertIn("103 tests", readme)
        self.assertIn("commercial implementation", readme.lower())
        self.assertIn("Ops Configuration", spec)
        self.assertIn("ops/opsconfig.yaml.example", spec)
        self.assertIn("/opt/aprp/checkout", spec)
        self.assertIn("storefront host", spec)
        self.assertIn("mirror hosts", spec)
        self.assertIn("aprp-server", spec)
        self.assertIn("aprp-mirror", spec)
        self.assertIn("DNS-01", spec)
        self.assertIn("certbot", spec.lower())
        self.assertIn("manual TXT", spec)
        self.assertIn("docs/pos.md", spec)
        self.assertIn("docs/couriers.md", spec)
        self.assertIn("docs/storefront.md", spec)
        self.assertIn("docs/showcase.md", spec)
        self.assertIn("docs/release.md", spec)
        self.assertIn("docs/install.md", spec)
        self.assertIn("docs/development.md", spec)
        self.assertIn("docs/security.md", spec)
        self.assertIn("docs/accounting.md", spec)
        self.assertIn("storefront host", plan)
        self.assertIn("mirror hosts", plan)
        self.assertIn("aprp-server", plan)
        self.assertIn("aprp-mirror", plan)
        self.assertIn("DNS-01", plan)
        self.assertIn("aprp.aprp.runtime_services", spec)
        self.assertIn("aprp.aprp.pos_services", spec)
        self.assertIn("aprp.aprp.storefront_services", spec)
        self.assertIn("aprp.aprp.showcase_services", spec)
        self.assertIn("aprp.aprp.courier_services", spec)
        self.assertIn("aprp.aprp.accounting_services", spec)
        self.assertNotIn("ops/demo_config.json", spec)
        self.assertIn("multi-location", plan)
        self.assertIn("POS", plan)
        self.assertIn("courier", plan)
        self.assertNotIn("Storefront demo milestone", plan)

    def test_version_anchor_is_present(self):
        """Ensure the repo version anchor is available for governance sync."""
        version = Path("VERSION").read_text(encoding="utf-8").strip()

        self.assertEqual("0.4.0", version)
