#!/usr/bin/env python3
"""Render the APRP GitHub workflow wrappers."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from textwrap import dedent

WORKFLOWS: dict[str, str] = {
    "deploy.yml": dedent(
        """\
        # Generated by ops/render_workflows.py. Edit the generator, not
        # this file, when the workflow wrapper changes.
        name: Deploy
        on:
          workflow_dispatch:
        jobs:
          deploy:
            name: Deploy primary stack
            runs-on:
              - self-hosted
              - aprp-primary
            permissions:
              contents: read
            defaults:
              run:
                shell: bash
            steps:
              - name: Run deploy script
                working-directory: /opt/aprp/APRP
                run: ./ops/deploy.sh
        """
    ),
    "backup.yml": dedent(
        """\
        # Generated by ops/render_workflows.py. Edit the generator, not
        # this file, when the workflow wrapper changes.
        name: Backup
        on:
          workflow_dispatch:
            inputs:
              command:
                description: Backup helper command
                required: true
                default: backup
                type: choice
                options:
                  - backup
                  - restore
                  - offsite-sync
              session_path:
                description: Optional session path for restore or sync
                required: false
                type: string
        jobs:
          backup:
            name: Run backup helper
            runs-on:
              - self-hosted
              - aprp-primary
            permissions:
              contents: read
            defaults:
              run:
                shell: bash
            steps:
              - name: Run backup script
                working-directory: /opt/aprp/APRP
                env:
                  APRP_BACKUP_COMMAND: ${{ inputs.command }}
                  APRP_BACKUP_SESSION_PATH: ${{ inputs.session_path }}
                run: |
                  backup_args=("${APRP_BACKUP_COMMAND}")
                  if [[ -n "${APRP_BACKUP_SESSION_PATH}" ]]; then
                    backup_args+=("${APRP_BACKUP_SESSION_PATH}")
                  fi
                  ./ops/backup.sh "${backup_args[@]}"
        """
    ),
    "mirror.yml": dedent(
        """\
        # Generated by ops/render_workflows.py. Edit the generator, not
        # this file, when the workflow wrapper changes.
        name: Mirror
        on:
          workflow_dispatch:
        jobs:
          mirror:
            name: Deploy mirror stack
            runs-on:
              - self-hosted
              - aprp-mirror
            permissions:
              contents: read
            defaults:
              run:
                shell: bash
            steps:
              - name: Run mirror script
                working-directory: /opt/aprp/APRP
                run: ./ops/deploy_mirror.sh
        """
    ),
    "recovery.yml": dedent(
        """\
        # Generated by ops/render_workflows.py. Edit the generator, not
        # this file, when the workflow wrapper changes.
        name: Recovery
        on:
          workflow_dispatch:
            inputs:
              command:
                description: Mirror recovery helper command
                required: true
                default: mirror-status
                type: choice
                options:
                  - mirror-status
                  - mirror-restore
                  - mirror-reseed
                  - mirror-rejoin
        jobs:
          recovery:
            name: Run recovery helper
            runs-on:
              - self-hosted
              - aprp-mirror
            permissions:
              contents: read
            defaults:
              run:
                shell: bash
            steps:
              - name: Run recovery script
                working-directory: /opt/aprp/APRP
                env:
                  APRP_RECOVERY_COMMAND: ${{ inputs.command }}
                run: ./ops/db_mirror_restore.sh "${APRP_RECOVERY_COMMAND}"
        """
    ),
}


def _write_workflows(output_dir: Path) -> None:
    """Write the tracked workflow wrappers to the requested directory."""

    output_dir.mkdir(parents=True, exist_ok=True)
    for file_name, content in WORKFLOWS.items():
        path = output_dir / file_name
        path.write_text(content.rstrip() + "\n", encoding="utf-8")


def _check_workflows(output_dir: Path) -> None:
    """Verify that the generated workflow wrappers match disk contents."""

    mismatches = []
    for file_name, content in WORKFLOWS.items():
        path = output_dir / file_name
        expected = content.rstrip() + "\n"
        if not path.exists():
            mismatches.append(f"missing: {path}")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            mismatches.append(f"mismatch: {path}")
    if mismatches:
        raise SystemExit("\n".join(mismatches))


def main(argv: list[str]) -> int:
    """Render or verify the APRP GitHub workflow wrappers."""

    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--output-dir",
        default=".github/workflows",
        help="Directory that should contain the generated wrappers.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify the tracked wrappers instead of writing them.",
    )
    args = parser.parse_args(argv)

    output_dir = Path(args.output_dir)
    if args.check:
        _check_workflows(output_dir)
    else:
        _write_workflows(output_dir)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
